
name: example notebooks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install
      run: |
        pip install .
    - name: Install paper depends
      run: |
    - name: Run Direct Regression
      run: jupyter nbconvert --ExecutePreprocessor.timeout=-1 --execute "examples/DirectRegression.ipynb" --to notebook --output-dir='temp' --clear-output
    - name: Run Metapop
      run: jupyter nbconvert --ExecutePreprocessor.timeout=-1 --execute "examples/Metapop.ipynb.ipynb" --to notebook --output-dir='temp' --clear-output
    - name: Run Quick_start
      run: jupyter nbconvert --ExecutePreprocessor.timeout=-1 --execute "examples/Quick_start.ipynb" --to notebook --output-dir='temp' --clear-output
    - name: Run SIR_Example
      run: jupyter nbconvert --ExecutePreprocessor.timeout=-1 --execute "examples/SIR_Example.ipynb" --to notebook --output-dir='temp' --clear-output
    - name: Run Traj_Matching
      run: jupyter nbconvert --ExecutePreprocessor.timeout=-1 --execute "examples/Traj_Matching.ipynb" --to notebook --output-dir='temp' --clear-output
